[book]
authors = [""]
language = "en"
multilingual = false
src = "src"
title = "Toronto Community Network"

[output.html]
theme = "theme"
additional-css = ["theme-ext/style.css"]
additional-js = ["theme-ext/sidebar.js"]

[output.linkcheck]
follow-web-links = true
warning-policy = "error"
exclude = ["https://cloud.tomesh.net","https://bitwarden.com"]
